# This workflow build and publish iOS artifacts to the LUKSO iOS SDK repository on Github

name: Upload iOS Github artifacts CD

on:
  # Run workflow manually for testing
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  upload-ios-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check if NPM package version has changed
        uses: EndBug/version-check@v1
        id: check

      - name: Use Node.js v16
        if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "npm"

      - if: steps.check.outputs.changed == 'true'
        run: npm ci

      - name: Write ABIs for iOS in Swift file
        if: steps.check.outputs.changed == 'true'
        run: |
          mkdir ios
          npx hardhat run make-ios.js

      - name: Push latest iOS artifacts to 'universalprofile-ios-sdk' repo
        if: steps.check.outputs.changed == 'true'
        run: |
          git clone https://.:${{ secrets.IOSSDK_GITHUB_REPO_KEY }}@github.com/lukso-network/universalprofile-ios-sdk.git
          cd universalprofile-ios-sdk
          git config --global user.email "release@lukso.network"
          git config --global user.name "LUKSO Bot"
          git push origin --delete abi-update-release
          git checkout -b abi-update-release
          cp ../ios/UPContractsAbi.swift universalprofile-ios-sdk/UPContractsAbi.swift
          git add .
          git commit -m "Automatic publish new contracts abis from lukso-network/lsp-universalprofile-smart-contracts"
          git push --set-upstream origin abi-update-release
