# This workflow build and publish iOS artifacts to the LUKSO iOS SDK repository on Github

name: Upload iOS Github artifacts CD

on:
  repository_dispatch:
    types: [trigger-release]

jobs:
  upload-ios-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-artifacts.yml
          workflow_conclusion: success
          name: UPContractsAbi.swift
          path: ios
          branch: main
          event: push

      - name: Push latest iOS artifacts to 'universalprofile-ios-sdk' repo
        run: |
          git clone https://.:${{ secrets.IOSSDK_GITHUB_REPO_KEY }}@github.com/lukso-network/universalprofile-ios-sdk.git
          cd universalprofile-ios-sdk
          git checkout main
          git config --global user.email "release@lukso.network"
          git config --global user.name "LUKSO Bot"
          if git show-ref --quiet abi-update-release; then
            git push origin --delete abi-update-release
          fi
          git checkout -b abi-update-release
          cp ../ios/UPContractsAbi.swift Sources/UniversalProfile/UPContractsAbi.swift
          git add .
          current_version=$(git describe --tags --abbrev=0)
          git commit -m "ci: automatic publish of new contracts ABIs ($current_version) from lukso-network/lsp-smart-contracts"
          git push --set-upstream origin abi-update-release
